### ISSUE TITLE
Account: Allow to apply custom label/annotation on namespace

### ISSUE THREAD

**Issue by cortex93** [loft-sh/kiosk#105]
The issue https://github.com/loft-sh/kiosk/issues/32 let an account to add predefined metadata on all namespaces. The idea is to open this possibility to some more dynamic value.
The use case is to be able for an account to label/annotate its namespaces with custom value so he can use label selector.

If security is a concern, maybe the space can allow only some prefix to be used.

```yaml
apiVersion: tenancy.kiosk.sh/v1alpha1
kind: Account
spec:
  space:
    # existing fields are kept
    allowCustomMetadata: true/false
    # or
    allowedCustomMetadataPrefixes:
      - custom.foo.bar/
```
```yaml
apiVersion: tenancy.kiosk.sh/v1alpha1
kind: Space
metadata:
  name: johns-space
spec:
  labels:
    env: test
    # or
    custom.foo.bar/env: test
  annotations:
    domain: bar    
    # or
    custom.foo.bar/domain: bar
```

Another design would be to replicate label and annotation present on the space itself.
```yaml
apiVersion: tenancy.kiosk.sh/v1alpha1
kind: Space
metadata:
  name: johns-space
  labels:
    env: test
    # or
    custom.foo.bar/env: test
  annotations:
    domain: bar    
    # or
    custom.foo.bar/domain: bar
spec:
```

**Comment by FabianKramm** [comment]
@cortex93 thanks for opening this issue! So currently it is possible to custom label and annotate a space as an account during space creation, you can always do something like:
```yaml
apiVersion: tenancy.kiosk.sh/v1alpha1
kind: Space
metadata:
  name: johns-space
  labels:
    env: test
    # or
    custom.foo.bar/env: test
  annotations:
    domain: bar    
    # or
    custom.foo.bar/domain: bar
spec:
   ...
```
and then do a `kubectl create -f space.yaml --as my-account`, which should work if the account can create spaces in the cluster.

As an admin you can also force certain labels/annotations on a space in the account spec:
```yaml
apiVersion: tenancy.kiosk.sh/v1alpha1
kind: Account
metadata:
  name: johns-account-default-space-metadata
spec:
  space: 
    clusterRole: kiosk-space-admin
    spaceTemplate:
      metadata:
        labels:
          some-label: "label-value"
          some-other-label: "other-label-value"
        annotations:
          "space-annotation-1": "annotation-value-1"
          "space-annotation-2": "annotation-value-2"
  subjects:
  - kind: User
    name: john
    apiGroup: rbac.authorization.k8s.io
```

These labels and annotations defined here will be forced on the space and cannot be changed in the space creation. 

Regarding updating labels and annotations on an existing space:
The account would need to get the RBAC update permissions for a space, which would allow him to also change the owning account or any other metadata on the space. If that is okay for you, you can always add this RBAC permission for the account and he will be able to change metadata freely.
