### ISSUE TITLE
Hey is it possible/ how to use kiosk with saml2-based ADFS ?

### ISSUE THREAD

**Issue by Kiddinglife** [loft-sh/kiosk#132]

**Comment by FabianKramm** [comment]
@Kiddinglife thanks for creating this issue! Kiosk uses the normal `Group` and `User` kind as you would use in any standard `RoleBinding` or `ClusterRoleBinding`:

```yaml
apiVersion: tenancy.kiosk.sh/v1alpha1
kind: Account
metadata:
  name: group-account
spec:
  subjects:
  - kind: Group
    name: my-group
    apiGroup: rbac.authorization.k8s.io
```

So as long as your authentication provider does fill the groups field correctly, it works perfectly fine with kiosk as well.
