### ISSUE TITLE
Account spaceTemplate is not reconciled

### ISSUE THREAD

**Issue by juv** [loft-sh/kiosk#133]
Hi, 

I'm using Kiosk 0.2.8 and got an Account with field `spec.space.spaceTemplate` to define Network Policies that should be present in each space of that account. Readme: https://github.com/loft-sh/kiosk#37-defaults-for-spaces

I have a `Template` resource which is used in that `Account` resource:
```
apiVersion: tenancy.kiosk.sh/v1alpha1
kind: Account
metadata:
  name: testbenchframework-account
  ...
spec:
  space:
    clusterRole: kiosk-space-admin
    limit: 2
    spaceTemplate:
      metadata:
        creationTimestamp: null
        labels:
          some/label: whatever-account
    templateInstances:
    - metadata:
        creationTimestamp: null
      spec:
        template: space-restrictions
```

```
apiVersion: config.kiosk.sh/v1alpha1
kind: Template
metadata:
  name: space-restrictions
  ...
resources:
  manifests:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-some-communication
    spec:
      ...
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-some-egress-communication
    spec:
      ...
```

Upon creation of the space, the template was successfully executed and I could see my Network Policy being created in the `Space`. Then, I went ahead and changed the template by adding a second Network Policy and let ArgoCD upgrade the resource.

Now, 30 minutes after the `Template` was changed in the cluster, the updated `Template` was still not executed in the `Space`. 
Is there a way to trigger the reconciliation of the template instances?

**Comment by juv** [comment]
Oh wow, right after writing this ticket, I saw this comment in the [docs](https://github.com/loft-sh/kiosk#55-templateinstances):
> TemplateInstances allow admins and user to see which Templates are being used within a Space/Namespace and **they make it possible to upgrade the resources created by a Template if there is a newer version of the Template (coming soon)**.

Unfortunately that link `coming soon` does not point to an anchor anymore? https://github.com/loft-sh/kiosk#roadmap

**Comment by FabianKramm** [comment]
@juv thanks for creating this issue! Thats actually possible, however you will need to add a `sync: true` for the template instance:
```yaml
apiVersion: tenancy.kiosk.sh/v1alpha1
kind: Account
metadata:
  name: testbenchframework-account
  ...
spec:
  space:
    clusterRole: kiosk-space-admin
    limit: 2
    spaceTemplate:
      metadata:
        creationTimestamp: null
        labels:
          some/label: whatever-account
    templateInstances:
    - metadata:
        creationTimestamp: null
      spec:
        template: space-restrictions
        sync: true
```

For already existing template instances in spaces you will need to set the `sync: true` field manually. 

After this field is set, it will sync changes from the template to the template instance that was created in the space and create the second network policy.
