### ISSUE TITLE
Unsupport kubernetes server-side apply

### ISSUE THREAD

**Issue by ywyt738** [loft-sh/kiosk#137]
```
apiVersion: tenancy.kiosk.sh/v1alpha1
kind: Account
metadata:
  name: e-chop-account
spec:
  subjects:
    - kind: User
      name: e-chop
      apiGroup: rbac.authorization.k8s.io
```

kubectl apply --dry-run=server --server-side -f account.yaml

error message:
UnsupportedMediaType, error: 415: Unsupported Media Type
