### ISSUE TITLE
Unable to create template instance with parameters

### ISSUE THREAD

**Issue by lamebear** [loft-sh/kiosk#146]
When trying to create a `TemplateInstance` resource for a `Template` that has parameters, the status of the resource has the message: `parameter TEST_NAME does not exist in template vcluster`

```
# template.yaml
apiVersion: config.kiosk.sh/v1alpha1
kind: Template
metadata:
  name: vcluster
  namespace: kiosk
resources:
  helm:
    releaseName: vcluster
    chart:
      repository:
        name: vcluster
        repoUrl: https://charts.loft.sh
        version: "0.11.1"
    values: |
      sync:
        serviceaccounts:
          enabled: true
      syncer:
        kubeConfigContextName: "${NAME}"
      ingress:
        enabled: true
        ingressClassName: nginx-internal
        host: "${NAME}.clusters.${PLATFORM}.my-domain.dev"
```

```
# template-instance.yaml
apiVersion: config.kiosk.sh/v1alpha1
kind: TemplateInstance
metadata:
  name: test-vcluster-vcluster
  namespace: test-vcluster-space
spec:
  parameters:
    - name: NAME
      value: test-vcluster-vcluster
    - name: PLATFORM
      value: moshpit
  template: vcluster
status:
  message: parameter NAME does not exist in template vcluster
  reason: ErrorValidatingParameters
  status: Failed
```

I've tried defining the parameters with `${{..}}`, `${..}`. and `$..` but none of them work.
Kiosk Version: v0.2.11
